
# html lang
language: zh

# main menu navigation
menu:
  Home: /
  About: /about

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css?family=Noto+Serif+SC:500,700|Abril+Fatface&display=swap # for font

# scripts loaded in the end of the body
scripts_defer:
- https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- /js/paper.js # for basic script


social:
  RSS 订阅: https://jopus.cn/atom.xml
  公开笔记: https://notes.jopus.cn
  # and more, you can add other link by the same way
# Uncomment to disable sidebar
# toc: false
# link: false
# archives: false
# categories: false
# tags: false

# theme color
main_color: default # forest | grass | sky | sun | sea | gray | default | red | black |

# google Analytics
google_analytics_id: G-Y6V8LR8RMR

# comment module
comment:
  enable: false
  type: utterances # valine | utterances

  # valine 需要的参数
  appId: your-app-id
  appKey: your-app-key
  placeholder: say something
  notify: false
  verify: false
  avatar: mp

  # utterances (https://utteranc.es/) 需要的参数
  repo: thejtf/thejtf.github.io
  issue_term: pathname
  theme: boxy-light
